#SPDX-License-Identifier: MIT-0
---
# vars file for mysql

mysql_root_password: "RootPass123!"
mysql_database: "rahulverse_db"
mysql_user: "rahulverse_user"
mysql_password: "UserPass123!"
db_host: "localhost"
# mysql_bind_address: "0.0.0.0"

