$ANSIBLE_VAULT;1.1;AES256
61393530356137626638313039633834386336363737386162653637643462653163313539613265
3733666231373532336332656132666333333461343335360a643134393465363235313139363731
34336131366233393964323932373935633863363931383462366361316237623033353131646161
3631376661303131350a353735373930633035313262353133666435383466376662636634666637
35633138663634306333653038323133643164633930366333653761383234333061373134353363
33353837616364346164656335373337336135666366386163633363383036616236346538633764
61336263623234616165383266333834386332663433346439326333336534316165323530383465
63366138643735613966636361653932636538323833653063323133343565633139363235636466
35616434636163303336646630613136373134303765316434303732633366626137373034396264
34613430643430633535373463363562363136656131653638366636303238373039373561363662
61633364396230356234633166343562323464383935333232633434366134616232666166623935
30333262373533326437633330386662626138343333376330393665616537356434346230336361
63353930323237313338316562316466396437623966613234376364336433303230376131643763
33393832313531656433666536613737386238383166633031333466343238346663646565626430
35656533643261636134613133306339333137373663633262376666306665316435303865343061
31353435353862636561333966343634333937623665633264653962633364653465623035633765
3634
