# SPDX-License-Identifier: MIT-0
---
springboot_app_name: rahulverse
springboot_app_path: /home/ubuntu/ansible_project/rahulverse-user-portal

springboot_remote_build_path: /tmp/rahulverse-build  

server_port: 8089
# db_host: "localhost"
db_host: 172.31.0.116
db_port: 3306
db_name: "{{ mysql_database }}"
db_user: "{{ mysql_user }}"
db_password: "{{ mysql_password }}"
